local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node

-- Helper function to capitalize first letter
local function capitalize(text)
	return text:sub(1, 1):upper() .. text:sub(2)
end

ls.add_snippets("typescriptreact", {
	s("useState", {
		t("const ["),
		i(1, "state"),
		t(", set"),
		f(function(args)
			return capitalize(args[1][1])
		end, { 1 }),
		t("] = useState<"),
		i(2, "type"),
		t(">("),
		i(3, "initialValue"),
		t(")"),
	}),
	s("range-input", {
		t({
			'<label htmlFor="range-input">Value</label>',
			"<input",
			'  id="range-input"',
			'  className="range-input"',
			'  type="range"',
			'  min="0"',
			'  max="100"',
			'  step="1"',
			'  value="50"',
			"/>",
		}),
	}),
})

ls.add_snippets("javascriptreact", {
	s("useState", {
		t("const ["),
		i(1, "state"),
		t(", set"),
		f(function(args)
			return capitalize(args[1][1])
		end, { 1 }),
		t("] = useState("),
		i(2, "initialValue"),
		t(")"),
	}),
	s("range-input", {
		t({
			'<label htmlFor="range-input">Value</label>',
			"<input",
			'  id="range-input"',
			'  className="range-input"',
			'  type="range"',
			'  min="0"',
			'  max="100"',
			'  step="1"',
			'  value="50"',
			"/>",
		}),
	}),
})

ls.add_snippets("html", {
	s("range-input", {
		t({
			'<label for="range-input">Value</label>',
			"<input",
			'  id="range-input"',
			'  class="range-input"',
			'  type="range"',
			'  min="0"',
			'  max="100"',
			'  step="1"',
			'  value="50"',
			"/>",
		}),
	}),
})

for _, ft in ipairs({ "css", "scss", "sass", "less" }) do
	ls.add_snippets(ft, {
		s("abs", {
			t("position: absolute;"),
			t({ "", "top: 50%;" }),
			t({ "", "left: 50%;" }),
			t({ "", "transform: translate(-50%, -50%);" }),
		}),
		s("range-input", {
			t({
				".range-input {",
				"  /* Track */",
				"  --range-track-height: 4px;",
				"  --range-track-background: transparent;",
				"  --range-track-filled-color: var(--ubilabs-white);",
				"  --range-track-unfilled-color: var(--ubilabs-blue-light-2);",
				"",
				"  /* Thumb */",
				"  --range-thumb-size: 1rem;",
				"  --range-thumb-border-width: 1px;",
				"  --range-thumb-border-color: var(--ubilabs-white);",
				"  --range-thumb-background: var(--ubilabs-blue);",
				"  --range-thumb-hover-background: var(--ubilabs-blue-light-1);",
				"",
				"  /* Focus */",
				"  --range-focus-inner-width: 2px;",
				"  --range-focus-outer-width: 4px;",
				"  --range-focus-inner-color: var(--ubilabs-blue-light-1);",
				"  --range-focus-outer-color: var(--ubilabs-white);",
				"",
				"  /* State */",
				"  --range-progress: 0%;",
				"  --range-fill-direction: to right;",
				"",
				"  appearance: none;",
				"  width: 100%;",
				"  height: 24px;",
				"  margin: 0;",
				"  padding: 0;",
				"  border: 0;",
				"  border-radius: 2px;",
				"  outline: 2px solid transparent;",
				"  outline-offset: 2px;",
				"  background:",
				"    linear-gradient(",
				"      var(--range-fill-direction),",
				"      var(--range-track-filled-color) 0 var(--range-progress),",
				"      var(--range-track-unfilled-color) var(--range-progress) 100%",
				"    )",
				"    center / 100% var(--range-track-height) no-repeat;",
				"  cursor: pointer;",
				"",
				"  &:dir(rtl) {",
				"    --range-fill-direction: to left;",
				"  }",
				"",
				"  /*",
				"   * Track",
				"   */",
				"",
				"  &::-webkit-slider-runnable-track {",
				"    box-sizing: border-box;",
				"    height: var(--range-track-height);",
				"    border: 0;",
				"    border-radius: 999px;",
				"    background: var(--range-track-background);",
				"  }",
				"",
				"  &::-moz-range-track {",
				"    box-sizing: border-box;",
				"    height: var(--range-track-height);",
				"    border: 0;",
				"    border-radius: 999px;",
				"    background: var(--range-track-background);",
				"  }",
				"",
				"  &::-moz-range-progress {",
				"    height: var(--range-track-height);",
				"    border-radius: 999px;",
				"    background: transparent;",
				"  }",
				"",
				"  /*",
				"   * Thumb",
				"   */",
				"",
				"  &::-webkit-slider-thumb {",
				"    appearance: none;",
				"    box-sizing: border-box;",
				"    width: var(--range-thumb-size);",
				"    height: var(--range-thumb-size);",
				"    margin-top: calc(",
				"      (var(--range-track-height) - var(--range-thumb-size)) / 2",
				"    );",
				"    border: var(--range-thumb-border-width) solid",
				"      var(--range-thumb-border-color);",
				"    border-radius: 50%;",
				"    background: var(--range-thumb-background);",
				"    cursor: grab;",
				"  }",
				"",
				"  &::-moz-range-thumb {",
				"    box-sizing: border-box;",
				"    width: var(--range-thumb-size);",
				"    height: var(--range-thumb-size);",
				"    border: var(--range-thumb-border-width) solid",
				"      var(--range-thumb-border-color);",
				"    border-radius: 50%;",
				"    background: var(--range-thumb-background);",
				"    cursor: grab;",
				"  }",
				"",
				"  /*",
				"   * Hover",
				"   */",
				"",
				"  @media (hover: hover) and (pointer: fine) {",
				"    &:not(:disabled):hover {",
				"      &::-webkit-slider-thumb {",
				"        background: var(--range-thumb-hover-background);",
				"      }",
				"",
				"      &::-moz-range-thumb {",
				"        background: var(--range-thumb-hover-background);",
				"      }",
				"    }",
				"  }",
				"",
				"  /*",
				"   * Active / dragging",
				"   */",
				"",
				"  &:not(:disabled):active {",
				"    &::-webkit-slider-thumb {",
				"      background: var(--range-thumb-hover-background);",
				"      cursor: grabbing;",
				"    }",
				"",
				"    &::-moz-range-thumb {",
				"      background: var(--range-thumb-hover-background);",
				"      cursor: grabbing;",
				"    }",
				"  }",
				"",
				"  /*",
				"   * Keyboard focus",
				"   */",
				"",
				"  &:focus-visible {",
				"    outline: none;",
				"",
				"    &::-webkit-slider-thumb {",
				"      box-shadow:",
				"        0 0 0 var(--range-focus-inner-width)",
				"          var(--range-focus-inner-color),",
				"        0 0 0 var(--range-focus-outer-width)",
				"          var(--range-focus-outer-color);",
				"    }",
				"",
				"    &::-moz-range-thumb {",
				"      box-shadow:",
				"        0 0 0 var(--range-focus-inner-width)",
				"          var(--range-focus-inner-color),",
				"        0 0 0 var(--range-focus-outer-width)",
				"          var(--range-focus-outer-color);",
				"    }",
				"  }",
				"",
				"  /*",
				"   * Invalid",
				"   */",
				"",
				'  &[aria-invalid="true"] {',
				"    &::-webkit-slider-thumb {",
				"      border-color: var(--range-error-color);",
				"    }",
				"",
				"    &::-moz-range-thumb {",
				"      border-color: var(--range-error-color);",
				"    }",
				"",
				"    &:focus-visible {",
				"      &::-webkit-slider-thumb {",
				"        box-shadow:",
				"          0 0 0 var(--range-focus-inner-width)",
				"            var(--range-focus-inner-color),",
				"          0 0 0 var(--range-focus-outer-width)",
				"            var(--range-error-color);",
				"      }",
				"",
				"      &::-moz-range-thumb {",
				"        box-shadow:",
				"          0 0 0 var(--range-focus-inner-width)",
				"            var(--range-focus-inner-color),",
				"          0 0 0 var(--range-focus-outer-width)",
				"            var(--range-error-color);",
				"      }",
				"    }",
				"  }",
				"",
				"  /*",
				"   * Disabled",
				"   */",
				"",
				"  &:disabled {",
				"    cursor: not-allowed;",
				"    opacity: 0.55;",
				"",
				"    &::-webkit-slider-thumb {",
				"      cursor: not-allowed;",
				"    }",
				"",
				"    &::-moz-range-thumb {",
				"      cursor: not-allowed;",
				"    }",
				"  }",
				"",
				"  /*",
				"   * Old Firefox focus border",
				"   */",
				"",
				"  &::-moz-focus-outer {",
				"    border: 0;",
				"  }",
				"",
				"  /*",
				"   * Windows High Contrast",
				"   */",
				"",
				"  @media (forced-colors: active) {",
				"    --range-track-filled-color: Highlight;",
				"    --range-track-unfilled-color: GrayText;",
				"    --range-thumb-background: Canvas;",
				"    --range-thumb-border-color: CanvasText;",
				"    --range-focus-inner-color: Canvas;",
				"    --range-focus-outer-color: Highlight;",
				"",
				"    forced-color-adjust: none;",
				"",
				"    &:disabled {",
				"      --range-track-filled-color: GrayText;",
				"      --range-thumb-border-color: GrayText;",
				"    }",
				"  }",
				"}",
			}),
		}),
		s("reset", {
			t({
				"@layer {",
				"\t*,",
				"\t*::before,",
				"\t*::after {",
				"\t\tbox-sizing: border-box;",
				"\t}",
				"",
				"\t* {",
				"\t\tmargin: 0;",
				"\t}",
				"",
				"\tbody {",
				"\t\tmin-height: 100vh;",
				"\t\tline-height: 1.5;",
				"\t\t-webkit-font-smoothing: antialiased;",
				"\t}",
				"",
				"\timg,",
				"\tpicture,",
				"\tvideo,",
				"\tcanvas,",
				"\tsvg {",
				"\t\tdisplay: block;",
				"\t\tmax-width: 100%;",
				"\t}",
				"",
				"\tinput,",
				"\tbutton,",
				"\ttextarea,",
				"\tselect {",
				"\t\tfont: inherit;",
				"\t}",
				"",
				"\tp,",
				"\th1,",
				"\th2,",
				"\th3,",
				"\th4,",
				"\th5,",
				"\th6 {",
				"\t\toverflow-wrap: break-word;",
				"\t}",
				"",
				"\tp {",
				"\t\ttext-wrap: pretty;",
				"\t}",
				"",
				"\th1,",
				"\th2,",
				"\th3,",
				"\th4,",
				"\th5,",
				"\th6 {",
				"\t\ttext-wrap: balance;",
				"\t}",
				"",
				"\t#root,",
				"\t#__next {",
				"\t\tisolation: isolate;",
				"\t}",
				"}",
			}),
		}),
	})
end
